export class userDetails{
    userId:number;
    empId:number;
    empName:string;
    emailId:string;
    contactNumber:string;
    status:number;
    groupId:number;
    group:string;
    regionId:number;
    region:string;
    roleId:number;
    role:string;
    image:string; 
    img:Array<any>;
    createdDate:string;
    createdById:number;
    createdBy:string;
    modifiedDate:string;
    modifiedById:number;
    modifiedBy:string;
    active:boolean;
    lastLoggedInDate:Date;
    regionsList:Array<any>;
    rolesList:Array<any>;
    userRegionsList:Array<any>;
    userRolesList:Array<any>;
    designation:string;
    
    constructor(obj){
        this.userId=obj.userId;
        this.empId=obj.empId;
        this.empName=obj.empName;
        this.emailId=obj.emailId;
        this.contactNumber=obj.contactNumber;
        this.status=obj.status;
        this.groupId=obj.groupId;
        this.group=obj.group;
        this.regionId=obj.regionId;
        this.region=obj.region;
        this.roleId=obj.roleId;
        this.role=obj.role;
        this.image=obj.image;
        this.img=obj.img; 
        this.createdDate=obj.createdDate;
        this.createdById=obj.createdById;
        this.createdBy=obj.createdBy;
        this.modifiedDate=obj.modifiedDate;
        this.modifiedById=obj.modifiedById;
        this.modifiedBy=obj.modifiedBy;
        this.designation=obj.designation;
        this.active=obj.active;
        this.lastLoggedInDate=obj.lastLoggedInDate;
        this.regionsList=obj.regionsList;
        this.rolesList=obj.rolesList;
        this.userRegionsList=obj.userRegionsList;
        this.userRolesList=obj.userRolesList;
    }
    }
